apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Otomasi-13"
  MYSQL_DATABASE: loginapp
  MYSQL_USER: loginuser
  MYSQL_PASSWORD: "Otomasi-13"